# [h-hg/yamb.yazi: Yet another bookmarks plugins. It supports persistence, jumping by a key, jumping by fzf.](https://github.com/h-hg/yamb.yazi)

# Yazi
[[mgr.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb --args=save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb --args=jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "G" ]
run = "plugin yamb --args=jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb --args=delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb --args=delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = [ "u", "A" ]
run = "plugin yamb --args=delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb --args=rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb --args=rename_by_fzf"
desc = "Rename bookmark by fzf"

# Diff
[[mgr.prepend_keymap]]
on   = [ "<C-d>" ]
run  = "plugin diff"
desc = "Diff the selected with the hovered file"

[[mgr.prepend_keymap]]
on   = [ "<C-l>" ]
run  = "plugin copy-md-link --sync --args='foo bar'"
desc = "Copy a markdown link to the hovered file"

[[mgr.prepend_keymap]]
on   = [ "<C-h>" ]
run  = "plugin copy-md-link"
desc = "Copy a markdown link to the hovered file"

[[mgr.prepend_keymap]]
on   = [ "u", "m"]
run = 'shell --confirm "notify-send $0 & disown"'
desc = "Just for test!"

[[mgr.prepend_keymap]]
on   = [ "u", "z"]
run = 'shell --confirm "ouch decompress $0 & disown"'
desc = "Just for test!"

[[mgr.prepend_keymap]]
on   = ["<C-s>"]
run = 'shell fish --block --confirm'
desc = "Fish"

[[mgr.prepend_keymap]]
on   = ["<C-x>"]
run = 'shell xonsh --block --confirm'
desc = "xonsh"

[[mgr.prepend_keymap]]
on   = ["<C-n>"]
run = 'shell nu --block --confirm'
desc = "Nushell"



# Duckdb Config

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"

# Editor commands
[[mgr.prepend_keymap]]
on = ["g", "e", "z"]
run = 'shell --confirm "zeditor $0 &"'
desc = "Open in Zed"

[[mgr.prepend_keymap]]
on = ["g", "e", "n"]
run = 'shell --confirm "neovide $0 &"'
desc = "Open in Neovide"

[[mgr.prepend_keymap]]
on = ["g", "e", "e"]
run = 'shell --confirm "emacs $0 &"'
desc = "Open in Emacs"
